plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

version = mod_version
group = maven_group

base {
    archivesName = "${mod_archive_name}-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.parchmentmc.org' }
}

neoForge {
    version = rootProject.neoforge_version

    parchment {
        minecraftVersion = rootProject.parchment_minecraft_version
        mappingsVersion = rootProject.parchment_mappings_version
    }

    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation project(':library_of_exile')
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            mod_id                : mod_id,
            mod_version           : mod_version,
            mod_display_name      : mod_display_name,
            mod_website_link      : mod_website_link,
            mod_issues_link       : mod_issues_link,
            minecraft_version     : minecraft_version,
            neoforge_version      : rootProject.neoforge_version,
            loader_version_range  : rootProject.loader_version_range,
            exile_library_version : exile_library_version
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
