org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

mod_version=1.1.3
minecraft_version=1.21.1
mod_website_link=https://www.curseforge.com/minecraft/mc-mods/dungeon-realm
mod_issues_link=https://github.com/RobertSkalko/dungeon_realm
mod_display_name=Dungeon Realm
mod_archive_name=Dungeon-Realm
mod_id=dungeon_realm
curse_id=1200770
modrinth_id=l7vS9yHb
release_type=release
maven_group=com.robertx22
exile_library_version=2.1.3
