modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "${mod_issues_link}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
displayURL = "${mod_website_link}"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Enter the realm of Infinite Dungeons!
'''

[[dependencies.dungeon_realm]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dungeon_realm]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dungeon_realm]]
modId = "library_of_exile"
type = "required"
versionRange = "[${exile_library_version},)"
ordering = "NONE"
side = "BOTH"
